In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df = df[['survived' ,'pclass', 'sex' , 'age' , 'fare' , 'embarked']]

In [5]:
df.head()

   survived  pclass     sex   age     fare embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [6]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
fare          0
embarked      2
dtype: int64

In [7]:
df.shape

(891, 6)

In [8]:
df.dropna(inplace = True)

In [9]:
df.shape

(712, 6)

In [10]:
from sklearn.preprocessing import LabelEncoder , StandardScaler

In [11]:
lb = LabelEncoder()

In [12]:
df['sex'] = lb.fit_transform(df['sex'])
df['embarked'] = lb.fit_transform(df['embarked'])

In [13]:
x = df.drop('survived' , axis = 1)
y = df['survived']

In [14]:
sc = StandardScaler()

In [15]:
x_scaled = sc.fit_transform(x)

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(x_scaled , y , test_size = 0.2 , random_state = 42)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
clf = KNeighborsClassifier(n_neighbors=7)

In [19]:
clf.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=7)

In [20]:
clf.score(X_test , y_test)

0.8111888111888111

In [21]:
pred = clf.predict(X_test)

In [22]:
from sklearn.metrics import classification_report

In [23]:
print(classification_report(y_test , pred))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84        80
           1       0.85      0.70      0.77        63

    accuracy                           0.81       143
   macro avg       0.82      0.80      0.80       143
weighted avg       0.82      0.81      0.81       143

In [24]:
  from sklearn.ensemble import RandomForestClassifier

In [25]:
clf1 = RandomForestClassifier(n_estimators=500)
clf1.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500)

In [26]:
clf1.score(X_test , y_test)

0.7692307692307693

In [27]:
from sklearn.datasets import fetch_california_housing

In [29]:
df1 = fetch_california_housing()

In [30]:
print(df1.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.